export const chatbotResponses = {
  'gopex': 'Gopex is a cutting-edge P2P Exchange platform that offers seamless currency exchange services. We provide a secure multi-currency wallet system with competitive rates and an upcoming international card feature. Our platform combines the best of traditional finance with modern technology.',
  'what is gopex': 'Gopex is your all-in-one financial platform featuring:\n• P2P Currency Exchange\n• Multi-currency Wallet\n• Upcoming International Card\n• Secure KYC Process\n• Real-time Exchange Rates\n• 24/7 Support',
  'platform': 'Gopex is designed to make international money transfers and currency exchange seamless. Our platform offers:\n• User-friendly interface\n• Real-time exchange rates\n• Multi-currency support\n• Bank-grade security\n• Fast KYC verification\n• Competitive fees',
  'features': 'Key features of Gopex include:\n• P2P Currency Exchange\n• Multi-currency Wallet\n• Real-time Rates\n• Secure Transactions\n• 24/7 Support\n• Coming Soon: International Card with zero foreign transaction fees',
  'exchange rates': 'Gopex offers competitive real-time exchange rates for multiple currencies including USD, EUR, GBP, JPY, and more. Our fee is only 0.2% per transaction.',
  'payment methods': 'Gopex supports multiple payment methods including credit/debit cards and bank transfers. All transactions are secured by Stripe.',
  'kyc': 'Our KYC (Know Your Customer) process is quick and secure. You\'ll need to provide basic personal information and verify your identity to start trading on Gopex.',
  'security': 'At Gopex, we prioritize your security. We use bank-grade encryption, secure payment processing, and continuous transaction monitoring for fraud prevention.',
  'currencies': 'Gopex supports major currencies including USD, EUR, GBP, JPY, AUD, CAD, CHF, and more. All managed in one secure multi-currency wallet.',
  'fees': 'Gopex charges a competitive 0.2% fee per transaction. No hidden charges! We believe in complete transparency.',
  'card': 'Coming Soon: The Gopex Card! Our international card will feature:\n• Zero foreign transaction fees\n• Multi-currency support\n• Real-time exchange rates\n• Worldwide acceptance\n• Digital and physical cards\n• Instant currency conversion',
  'wallet': 'The Gopex Multi-currency Wallet allows you to:\n• Hold multiple currencies\n• Convert instantly between currencies\n• Send money internationally\n• Track all transactions\n• Secure your funds\n• Connect to your Gopex Card (coming soon)',
  'help': 'I can help you learn about Gopex\'s features including our exchange platform, multi-currency wallet, upcoming card, security features, supported currencies, and fees. What would you like to know?',
  'about': 'Gopex is a secure P2P Exchange platform revolutionizing international money transfers. We combine multi-currency wallets, competitive exchange rates, and an upcoming international card to provide a complete financial solution.',
  'contact': 'You can reach our Gopex support team 24/7 through:\n• Live Chat\n• Email: support@gopex.com\n• Contact Form on our website\nWe typically respond within minutes!',
  'benefits': 'Choosing Gopex gives you:\n• Competitive exchange rates\n• Secure transactions\n• Multi-currency wallet\n• Fast processing\n• 24/7 support\n• Upcoming international card\n• User-friendly platform',
  'how it works': 'Getting started with Gopex is easy:\n1. Sign up and complete KYC\n2. Add funds to your wallet\n3. Exchange currencies at great rates\n4. Transfer money globally\n5. Soon: Use Gopex Card for payments',
}; 